### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/garyfeng/Library/Application Sup...

### ISSUE THREAD

**Issue by garyfeng** [atom/grammar-selector#27] opened 2015-11-08 17:17 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [grammar-selector](https://github.com/atom/grammar-selector) package, v0.47.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2'

```
At ATOM_SHELL_ASAR.js:118

Error: ENOENT: no such file or directory, lstat '/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
  at toRealPath (module.js:108:13)
  at tryFile (module.js:104:22)
  at tryExtensions (module.js:114:20)
  at tryPackage (module.js:92:31)
  at Function.Module._findPath (module.js:155:20)
  at Module._resolveFilename (module.js:332:25)
  at Function.Module._resolveFilename (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/node_modules/grammar-selector/lib/grammar-list-view.js:6:20)
  at Object.<anonymous> (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/node_modules/grammar-selector/lib/grammar-list-view.js:111:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at atom-text-editor.createGrammarListView (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/node_modules/grammar-selector/lib/main.js:45:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at grammar-selector-status.<anonymous> (/Users/garyfeng/Library/Application Support/com.github.atom.ShipIt/update.LarbMu2/Atom.app/Contents/Resources/app.asar/node_modules/grammar-selector/lib/grammar-status-view.js:54:32)

```

### Commands

```
  5x -2:41 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.6.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 grammar-selector:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-13 21:28
Closing as a duplicate of atom/atom#7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-13 21:28 UTC
Labels: uncaught-exception
