### ISSUE TITLE
setting to map a file to a grammar

### ISSUE THREAD

**Issue by kevwil** [atom/grammar-selector#18] opened 2015-05-06 19:29 UTC
I've been writing quite a few Go template files lately, and Atom never picks the Go Template grammar. It would be great if there were a setting where I could map all my *.ctmpl files to that grammar.

**Comment by lee-dohm** [comment] 2015-05-07 01:21
This is a duplicate of atom/atom#1718. Please subscribe there for updates.

**Closed by lee-dohm** 2015-05-07 01:21 UTC
